netbox:
  updateStrategy: 
    type: Recreate
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: netbox.sievert.fun
        paths:
          - /
    tls:
      - secretName: netbox-tls
        hosts:
          - netbox.sievert.fun