netbox:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - netbox.sievert.fun
    tls:
      - secretName: netbox-tls
        hosts:
          - netbox.sievert.fun