apiVersion: apps/v1
kind: Deployment
metadata:
  name: vshass
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vshass
  template:
    metadata:
      labels:
        app: vshass
    spec:
      volumes:
        - name: hass-pv-storage
          persistentVolumeClaim:
            claimName: hass-pv-claim
      containers:
        - image: codercom/code-server:3.1.1
          name: vshass
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/config"
            name: hass-pv-storage