apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cyberglitch-issuer
spec:
  acme:
    ...
    solvers:
    - dns01:
        cloudflare:
          email: jsievert@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token