apiVersion: apps/v1
kind: Deployment
metadata:
  name: btmon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-btmon-btmon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-10-01T03:10:29Z"
      labels:
        workload.user.cattle.io/workloadselector: deployment-btmon-btmon
    spec:
      containers:
      - args:
        - -c
        - /opt/btmon/btmon.py -c /config/btmon.cfg
        command:
        - /bin/sh
        image: rwojo/btmon-influx
        imagePullPolicy: Always
        name: btmon
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: btmoncfg
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          name: btmon-cfg
          optional: false
        name: btmoncfg