apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole
spec:
  rules:
  - host: pihole.xip.io
    http:
      paths:
      - backend:
          serviceName: pihole-tcp
          servicePort: 80
