apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
spec:
  externalTrafficPolicy: Local
  healthCheckNodePort: 30331
  loadBalancerIP: 192.168.100.40
  ports:
  - name: dns
    nodePort: 31990
    port: 53
    protocol: UDP
    targetPort: dns
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer