apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
spec:
  clusterIP: 10.43.38.171
  externalTrafficPolicy: Local
  ports:
  - name: dns-udp
    nodePort: 31427
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: client-udp
    nodePort: 32016
    port: 67
    protocol: UDP
    targetPort: client-udp
  selector:
    app: pihole
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}