apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssltest
spec:
  rules:
  - host: ssltest.cyberglitch.dev
    http:
      paths:
      - backend:
          serviceName: ssltest
          servicePort: 80