grafana:
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - grafana.sievert.fun
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.sievert.fun
  persistence:
    enabled: true
    size: 2Gi
