apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ddns
  template:
    metadata:
      labels:
        app: ddns
    spec:
      containers:
        - image: oznu/cloudflare-ddns
          name: ddns
          env:
            - name: ZONE
              value: "sievert.fun"
            - name: ZONE
              value: "home"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: CF_KEY
                  key: API_KEY