grafana:
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - chronograf.sievert.fun
    tls:
      - secretName: chronograf-tls
        hosts:
          - chronograf.sievert.fun
  persistence:
    enabled: true
    size: 1Gi
