esphome:
  deploymentStrategy:
    type: Recreate
  timezone: "America/Chicago"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    hosts:
      - esphome.sievert.fun
    tls:
      - secretName: esphome-tls
        hosts:
          - esphome.sievert.fun