apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronograf-pv-claim
spec:
  storageClassName: longhorn-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi