influxdb:
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    certManger: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - name: influxdb.sievert.fun
        path: /
    tls:
    - hosts:
      - influxdb.sievert.fun
      secretName: influxdb-tls
  persistence:
    enabled: true
    size: 10Gi
